name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check for tests
        id: check-tests
        run: |
          if [ -f package.json ] && grep -q '"test":' package.json; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        if: steps.check-tests.outputs.has_tests == 'true'
        run: |
          mkdir -p test-results
          npm test > test-results/results.txt

      - name: Upload test results
        if: steps.check-tests.outputs.has_tests == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/results.txt

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test artifact
        if: needs.test.outputs.has_tests == 'true'
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Show test result content
        if: needs.test.outputs.has_tests == 'true'
        run: cat results.txt

      - name: Install dependencies
        run: npm install

      - name: Install PM2 globally
        shell: cmd
        run: npm install -g pm2

      - name: Restart application
        shell: cmd
        run: |
          pm2 stop app || ver > nul
          pm2 start index.js --name app
